spring:
  security:
    user:
      name: admin
      password: admin

  datasource:
    username: root
    password: Arsenyars25
    url: jdbc:mysql://localhost:3306/insurance


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true



